# Generated by Django 5.0.3 on 2024-03-17 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='usuarios_pe_id_37d232_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('num_boleta', models.CharField(max_length=255, unique=True)),
                ('carrera', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=50)),
                ('nombre_protocolo', models.CharField(max_length=50)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona')),
            ],
            options={
                'ordering': ['num_boleta'],
                'indexes': [models.Index(fields=['num_boleta'], name='usuarios_al_num_bol_629fe3_idx')],
            },
        ),
    ]
